### ISSUE TITLE
Ruby Gem::Exception can't find executable fir

### ISSUE THREAD

**Issue by craone** [FIRHQ/fir-cli#111]
请问，我用fastlane打包后执行 system "fir me" （fir命令都会报错）
```
/Users/one/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/rubygems_integration.rb:393:in `block in replace_bin_path': can't find executable fir (Gem::Exception)
	from /Users/aone/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/rubygems_integration.rb:410:in `block in replace_bin_path'
	from /Users/aone/.rvm/gems/ruby-2.3.0/bin/fir:22:in `<main>'
	from /Users/aone/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/aone/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```
是什么原因造成的？麻烦给个解决方法，谢谢。

**Comment by al03** [comment]
+1

**Comment by craone** [comment]
暂时解决了，可能是ruby版本不兼容导致的。
大家可以先下载
`ruby-2.1.4
fastlane 1.110.0
fir-cli 1.5.0`
来运行脚本。本人采用如下版本型号，一切正常。坐等作者更新哈！

**Comment by zhaoyunyi** [comment]
我的 ruby-2.2.4 fastlane 2.14.2   fir-cli 1.5.0
不支持，感觉是不是 fastlane 的版本太高了，不兼容可能
