### ISSUE TITLE
在 jenkins 中使用 fir-cli 上传 ipa 报错

### ISSUE THREAD

**Issue by huaf22** [FIRHQ/fir-cli#112]
在 jenkins 中使用 fir-cli 上传 ipa 报错, 但是如果在这台电脑的命令行环境就正常上传
```
-- Control frame information -----------------------------------------------
c:0031 p:-17557559888626 s:0095 e:000094 TOP    [FINISH]
c:0030 p:---- s:0093 e:000092 CFUNC  :require
c:0029 p:0009 s:0089 e:000088 CLASS  /usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.3/lib/json/ext.rb:13
c:0028 p:0011 s:0087 e:000086 CLASS  /usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.3/lib/json/ext.rb:12
c:0027 p:0057 s:0085 e:000084 TOP    /usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.3/lib/json/ext.rb:9 [FINISH]
c:0026 p:---- s:0083 e:000082 CFUNC  :require
c:0025 p:0019 s:0079 e:000078 CLASS  /usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.3/lib/json.rb:58
c:0024 p:0017 s:0077 e:000076 TOP    /usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.3/lib/json.rb:54 [FINISH]
c:0023 p:---- s:0075 e:000074 CFUNC  :require
c:0022 p:0009 s:0071 e:000070 METHOD /usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types/loader.rb:226
c:0021 p:0011 s:0067 e:000066 BLOCK  /usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types/loader.rb:63 [FINISH]
c:0020 p:---- s:0063 e:000062 CFUNC  :each
c:0019 p:0020 s:0060 e:000059 METHOD /usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types/loader.rb:62
c:0018 p:0050 s:0057 e:000056 METHOD /usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types/loader.rb:88
c:0017 p:0019 s:0053 e:000052 METHOD /usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types/loader.rb:113
c:0016 p:0049 s:0049 e:000048 METHOD /usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types.rb:296
c:0015 p:0269 s:0045 e:000044 CLASS  /usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types.rb:323
c:0014 p:0046 s:0043 e:000042 TOP    /usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types.rb:63 [FINISH]
c:0013 p:---- s:0041 e:000040 CFUNC  :require
c:0012 p:0015 s:0037 e:000036 TOP    /usr/local/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:2 [FINISH]
c:0011 p:---- s:0035 e:000034 CFUNC  :require
c:0010 p:0123 s:0031 e:000030 TOP    /usr/local/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient.rb:10 [FINISH]
c:0009 p:---- s:0029 e:000028 CFUNC  :require
c:0008 p:0020 s:0025 e:000024 TOP    /usr/local/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/rest-client.rb:2 [FINISH]
c:0007 p:---- s:0023 e:000022 CFUNC  :require
c:0006 p:0031 s:0019 e:000018 TOP    /usr/local/lib/ruby/gems/2.3.0/gems/fir-cli-1.5.0/lib/fir.rb:6 [FINISH]
c:0005 p:---- s:0017 e:000016 CFUNC  :require_relative
c:0004 p:0007 s:0013 e:000012 TOP    /usr/local/lib/ruby/gems/2.3.0/gems/fir-cli-1.5.0/bin/fir:4 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :load
c:0002 p:0134 s:0006 E:002358 EVAL   /usr/local/bin/fir:23 [FINISH]
c:0001 p:0000 s:0002 E:000d58 TOP    [FINISH]

/usr/local/bin/fir:23:in `<main>'
/usr/local/bin/fir:23:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/fir-cli-1.5.0/bin/fir:4:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/fir-cli-1.5.0/bin/fir:4:in `require_relative'
/usr/local/lib/ruby/gems/2.3.0/gems/fir-cli-1.5.0/lib/fir.rb:6:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/fir-cli-1.5.0/lib/fir.rb:6:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/rest-client.rb:2:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/rest-client.rb:2:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient.rb:10:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient.rb:10:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:2:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb:2:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types.rb:63:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types.rb:323:in `<class:Types>'
/usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types.rb:296:in `load_default_mime_types'
/usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types/loader.rb:113:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types/loader.rb:88:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types/loader.rb:62:in `load_json'
/usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types/loader.rb:62:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types/loader.rb:63:in `block in load_json'
/usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types/loader.rb:226:in `load_from_json'
/usr/local/lib/ruby/gems/2.3.0/gems/mime-types-2.99.3/lib/mime/types/loader.rb:226:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.3/lib/json.rb:54:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.3/lib/json.rb:58:in `<module:JSON>'
/usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.3/lib/json.rb:58:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.3/lib/json/ext.rb:9:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.3/lib/json/ext.rb:12:in `<module:JSON>'
/usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.3/lib/json/ext.rb:13:in `<module:Ext>'
/usr/local/lib/ruby/gems/2.3.0/gems/json-1.8.3/lib/json/ext.rb:13:in `require'

```

**Comment by al03** [comment]
fir-cli依赖rest-client的1.7.0版本，对于rest-client的高版本不支持。

```
//列出已安装的rest-client
gem list rest-client
//选择删除大于1.7.0的版本
gem uninstall rest-client 
gem install rest-client -v 1.7.0
```

希望 @NaixSpirit 做一下对rest-client新版本依赖的支持。🙏

**Comment by NaixSpirit** [comment]
@al03 目前我没有权限开发 fir-cli
可以发邮件给 dev@fir.im 找相关开发人员
