### ISSUE TITLE
window下jenkins集成fir-cli出错

### ISSUE THREAD

**Issue by Nstd** [FIRHQ/fir-cli#13]
环境：
windows 7中使用jenkins，调用cygwin中的sh执行shell脚本（脚本内容是调用fir.bat发布应用：/cygdrive/d/Ruby22-x64/bin/fir.bat p "$UPLOAD_FILE" -T $USER_TOKEN）
执行出错：
...D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:1097:in `<module:RbReadline>': HOME environment variable (or HOMEDRIVE and HOMEPATH) must be set and point to a directory (RuntimeError)
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rbreadline.rb:17:in `<top (required)>'
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/readline.rb:10:in `<module:Readline>'
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/readline.rb:8:in `<top (required)>'
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/line_editor/readline.rb:2:in `<top (required)>'
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/line_editor.rb:2:in `<top (required)>'
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:8:in `<top (required)>'
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:2:in `<top (required)>'
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from D:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/fir-cli-1.2.1/lib/fir.rb:3:in `<top (required)>'
	from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/fir-cli-1.2.1/bin/fir:4:in `require_relative'
	from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/fir-cli-1.2.1/bin/fir:4:in `<top (required)>'
	from D:/Ruby22-x64/bin/fir:23:in `load'
	from D:/Ruby22-x64/bin/fir:23:in `<main>'
...

**Comment by Nstd** [comment]
在cygwin下获取这三个变量的值：HOME、HOMEDRIVE、HOMEPATH，然后设置到脚本中就可以了
