### ISSUE TITLE
iOS 上传失败

### ISSUE THREAD

**Issue by chenfengfeng** [FIRHQ/fir-cli#183]
版本:fir-cli 1.6.4
安装采取第三方方案
$ echo 'gem: --bindir /usr/local/bin' >> ~/.gemrc
$ gem install fir-cli
安装成功,调用 login 也能成功获取信息
然后调用上传
报错
```
chenzefengdeiMac:xi 2018-03-29 13-54-10 fengfeng$ fir publish xi.ipa
I, [2018-03-29T15:33:39.088174 #65164]  INFO -- : Publishing app via CZF-峰峰<315871438@qq.com>.......
I, [2018-03-29T15:33:39.088266 #65164]  INFO -- : ✈ -------------------------------------------- ✈
I, [2018-03-29T15:33:39.991374 #65164]  INFO -- : Fetching com.gmdoc.xi@fir.im uploading info......
I, [2018-03-29T15:33:39.991623 #65164]  INFO -- : Uploading app: xi-1.0(Build 1)
I, [2018-03-29T15:33:40.280040 #65164]  INFO -- : Uploading app icon......
I, [2018-03-29T15:33:40.280135 #65164]  INFO -- : Converting app's icon......
I, [2018-03-29T15:33:40.973829 #65164]  INFO -- : Uploading app binary......
closed stream
/usr/local/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:163:in `read'
/usr/local/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:163:in `create_file_field'
/usr/local/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:137:in `block in build_stream'
/usr/local/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `each'
/usr/local/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `each_with_index'
/usr/local/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `build_stream'
/usr/local/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:47:in `initialize'
/usr/local/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:16:in `new'
/usr/local/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/payload.rb:16:in `generate'
/usr/local/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:77:in `initialize'
/usr/local/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `new'
/usr/local/lib/ruby/gems/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/usr/local/lib/ruby/gems/2.4.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:63:in `block in basic_request'
/usr/local/lib/ruby/gems/2.4.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `times'
/usr/local/lib/ruby/gems/2.4.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `basic_request'
/usr/local/lib/ruby/gems/2.4.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:17:in `block (2 levels) in <module:DefaultRestModule>'
/usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.4/lib/fir/util/publish.rb:57:in `upload_file'
/usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.4/lib/fir/util/publish.rb:48:in `block (2 levels) in <module:Publish>'
/usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.4/lib/fir/util/publish.rb:40:in `upload_app'
/usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.4/lib/fir/util/publish.rb:16:in `publish'
/usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.4/lib/fir/cli.rb:116:in `publish'
/usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.4/lib/fir/cli.rb:181:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/fir-cli-1.6.4/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:22:in `load'
/usr/local/bin/fir:22:in `<main>'
```

**Comment by jicheng1014** [comment]
是否是在境外访问的 ?

**Comment by chenfengfeng** [comment]
@jicheng1014 没有哦,在国内,也没开 VPN

**Comment by chenfengfeng** [comment]
@jicheng1014 啊~果然是网络的问题,我切换了网络就正常, fir 能不能做个网络监测,不然报错也很难理解

**Comment by jicheng1014** [comment]
ok   这个地方我们写个东西处理下

**Comment by jicheng1014** [comment]
先做了个 timeout 300的更新我们这边     也可以使用 FIR_TIMEOUT 进行自定义

ps   您这边出问题的网络是?   我这边也跟cdn 厂商去反馈一下

**Comment by chenfengfeng** [comment]
@jicheng1014 我发现原来是路由做了代理的关系,代理香港地址,是不是只能在国内用?

**Comment by jicheng1014** [comment]
倒也不是  之前的超时设置的是5秒     照常理来说5秒海外也能建立握手, 只不过这个与cdn 提供的服务有关系.

**Comment by chenfengfeng** [comment]
嗯嗯,但目前来说我不使用代理是没问题的~谢谢~
