### ISSUE TITLE
Gem::ConflictError

### ISSUE THREAD

**Issue by akindone** [FIRHQ/fir-cli#185]
执行publish命令时报错如下 fir publish /Users/Shared/Jenkins/Home/workspace/xxx.ipa -T xxx
```
11:54:07 /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate fir-cli-1.6.6, because CFPropertyList-3.0.0 conflicts with CFPropertyList (~> 2.3) (Gem::ConflictError)
11:54:07 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
11:54:07 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
11:54:07 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
11:54:07 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
11:54:07 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
11:54:07 	from /Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.6/lib/fir.rb:22:in `<top (required)>'
11:54:07 	from /Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.6/bin/fir:4:in `require_relative'
11:54:07 	from /Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.6/bin/fir:4:in `<top (required)>'
11:54:07 	from /usr/local/bin/fir:22:in `load'
11:54:07 	from /usr/local/bin/fir:22:in `<main>'```

**Comment by akindone** [comment]
发现是电脑的gem需要更新，更新后需要重新install fir
```
$ gem sources --add https://gems.ruby-china.org/ --remove https://rubygems.org/
$ gem sources -l
*** CURRENT SOURCES ***

https://gems.ruby-china.org
# 请确保只有 gems.ruby-china.org
$ gem update --system
```
