### ISSUE TITLE
closed stream的问题

### ISSUE THREAD

**Issue by BianXiaoYan** [FIRHQ/fir-cli#188]
在国内用阿里云上传出现以下错误：
`closed stream
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/payload.rb:167:in `close'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/payload.rb:167:in `ensure in create_file_field'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/payload.rb:167:in `create_file_field'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/payload.rb:137:in `block in build_stream'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `each'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `each_with_index'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/payload.rb:134:in `build_stream'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/payload.rb:47:in `initialize'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/payload.rb:16:in `new'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/payload.rb:16:in `generate'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/request.rb:77:in `initialize'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `new'
/usr/local/share/gems/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/usr/local/share/gems/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:63:in `block in basic_request'
/usr/local/share/gems/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `times'
/usr/local/share/gems/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `basic_request'
/usr/local/share/gems/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:17:in `block (2 levels) in <module:DefaultRestModule>'
/usr/local/share/gems/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:65:in `upload_file'
/usr/local/share/gems/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:56:in `block (2 levels) in <module:Publish>'
/usr/local/share/gems/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:45:in `upload_app'
/usr/local/share/gems/gems/fir-cli-1.6.6/lib/fir/util/publish.rb:16:in `publish'
/usr/local/share/gems/gems/fir-cli-1.6.6/lib/fir/cli.rb:119:in `publish'
/usr/local/share/gems/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/usr/local/share/gems/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/share/gems/gems/fir-cli-1.6.6/lib/fir/cli.rb:184:in `invoke_command'
/usr/local/share/gems/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/usr/local/share/gems/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/usr/local/share/gems/gems/fir-cli-1.6.6/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:23:in `load'
/usr/local/bin/fir:23:in `<main>'
`
也设置了超时时间。请问是怎么回事？？

**Comment by jicheng1014** [comment]
这个我们联系下cdn 厂商

**Comment by jicheng1014** [comment]
Hello  我们与cdn 厂商确认了下   他们在昨天下午17:00左右部分地区有故障
