### ISSUE TITLE
在`fir publish xxxx`命令 添加`--password=xxx`参数之后 报错: `wrong header line format`

### ISSUE THREAD

**Issue by AbnerChen028** [FIRHQ/fir-cli#208]
具体错误信息如下:

```
wrong header line format
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http/response.rb:63:in `each_response_header'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http/response.rb:31:in `read_new'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:1423:in `block in transport_request'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:1420:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:1420:in `transport_request'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:1393:in `request'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:446:in `net_http_do_request'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:721:in `block in transmit'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/Library/Ruby/Gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/Library/Ruby/Gems/2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:63:in `block in basic_request'
/Library/Ruby/Gems/2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `times'
/Library/Ruby/Gems/2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:61:in `basic_request'
/Library/Ruby/Gems/2.3.0/gems/api_tools-0.0.6/lib/api_tools/default_rest_module.rb:17:in `block (2 levels) in <module:DefaultRestModule>'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.10/lib/fir/util/publish.rb:143:in `update_app_info'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.10/lib/fir/util/publish.rb:45:in `upload_app'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.10/lib/fir/util/publish.rb:16:in `publish'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.10/lib/fir/cli.rb:118:in `publish'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.10/lib/fir/cli.rb:183:in `invoke_command'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.10/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:22:in `load'
/usr/local/bin/fir:22:in `<main>'
```

**Comment by AbnerChen028** [comment]
version:   fir-cli 1.6.10

**Comment by jicheng1014** [comment]
诶  好奇怪  我这ok 呢

**Comment by jicheng1014** [comment]
我测试了下这个 带password的  似乎可以


麻烦把您的apk包 和短地址, 和你使用的具体指令, 都贴一下  我这看看是啥情况
