### ISSUE TITLE
安装后执行`fir help`命令报错

### ISSUE THREAD

**Issue by xx-li** [FIRHQ/fir-cli#211]
```
sudo gem install fir-cli  -n /usr/local/bin
Fetching: thor-0.20.0.gem (100%)
Successfully installed thor-0.20.0
Fetching: unf_ext-0.0.7.5.gem (100%)
Building native extensions. This could take a while...
Successfully installed unf_ext-0.0.7.5
Fetching: unf-0.1.4.gem (100%)
Successfully installed unf-0.1.4
Fetching: domain_name-0.5.20180417.gem (100%)
Successfully installed domain_name-0.5.20180417
Fetching: http-cookie-1.0.3.gem (100%)
Successfully installed http-cookie-1.0.3
Fetching: mime-types-data-3.2018.0812.gem (100%)
Successfully installed mime-types-data-3.2018.0812
Fetching: mime-types-3.2.2.gem (100%)
Successfully installed mime-types-3.2.2
Fetching: netrc-0.11.0.gem (100%)
Successfully installed netrc-0.11.0
Fetching: rest-client-2.0.2.gem (100%)
Successfully installed rest-client-2.0.2
Fetching: rubyzip-1.2.2.gem (100%)
Successfully installed rubyzip-1.2.2
Fetching: ruby_android-0.7.7.gem (100%)
Successfully installed ruby_android-0.7.7
Fetching: chunky_png-1.3.10.gem (100%)
Successfully installed chunky_png-1.3.10
Fetching: rqrcode-0.10.1.gem (100%)
Successfully installed rqrcode-0.10.1
Fetching: CFPropertyList-3.0.0.gem (100%)
Successfully installed CFPropertyList-3.0.0
Fetching: oj-3.6.8.gem (100%)
Building native extensions. This could take a while...
Successfully installed oj-3.6.8
Fetching: api_tools-0.0.6.gem (100%)
Successfully installed api_tools-0.0.6
Fetching: atomos-0.1.3.gem (100%)
Successfully installed atomos-0.1.3
Fetching: claide-1.0.2.gem (100%)
Successfully installed claide-1.0.2
Fetching: colored2-3.1.2.gem (100%)
Successfully installed colored2-3.1.2
Fetching: nanaimo-0.2.6.gem (100%)
Successfully installed nanaimo-0.2.6
Fetching: xcodeproj-1.6.0.gem (100%)
Successfully installed xcodeproj-1.6.0
Fetching: fir-cli-1.6.11.gem (100%)

        ______________        ________    ____
       / ____/  _/ __ \      / ____/ /   /  _/
      / /_   / // /_/ /_____/ /   / /    / /
     / __/ _/ // _, _/_____/ /___/ /____/ /
    /_/   /___/_/ |_|      \____/_____/___/

  ## 更新记录
  - (1.6.11) 变化了 ruby gem 仓库地址
  - (1.6.10) 增加显示release_id 以及 app_id
  - (1.6.9) 取消了依赖 cfpropertylist 的具体版本号
  - (1.6.8) 取消了远端回调, 改为本地callback
  - (1.6.8) fir-cli 也支持了私有部署模式
  - [fir-cli](https://github.com/firhq/fir-cli) 已经开源
  - 欢迎 fork, issue 和 pull request

Successfully installed fir-cli-1.6.11
Parsing documentation for thor-0.20.0
Installing ri documentation for thor-0.20.0
Parsing documentation for unf_ext-0.0.7.5
Installing ri documentation for unf_ext-0.0.7.5
Parsing documentation for unf-0.1.4
Installing ri documentation for unf-0.1.4
Parsing documentation for domain_name-0.5.20180417
Installing ri documentation for domain_name-0.5.20180417
Parsing documentation for http-cookie-1.0.3
Installing ri documentation for http-cookie-1.0.3
Parsing documentation for mime-types-data-3.2018.0812
Installing ri documentation for mime-types-data-3.2018.0812
Parsing documentation for mime-types-3.2.2
Installing ri documentation for mime-types-3.2.2
Parsing documentation for netrc-0.11.0
Installing ri documentation for netrc-0.11.0
Parsing documentation for rest-client-2.0.2
Installing ri documentation for rest-client-2.0.2
Parsing documentation for rubyzip-1.2.2
Installing ri documentation for rubyzip-1.2.2
Parsing documentation for ruby_android-0.7.7
Installing ri documentation for ruby_android-0.7.7
Parsing documentation for chunky_png-1.3.10
Installing ri documentation for chunky_png-1.3.10
Parsing documentation for rqrcode-0.10.1
Installing ri documentation for rqrcode-0.10.1
Parsing documentation for CFPropertyList-3.0.0
Installing ri documentation for CFPropertyList-3.0.0
Parsing documentation for oj-3.6.8
Installing ri documentation for oj-3.6.8
Parsing documentation for api_tools-0.0.6
Installing ri documentation for api_tools-0.0.6
Parsing documentation for atomos-0.1.3
Installing ri documentation for atomos-0.1.3
Parsing documentation for claide-1.0.2
Installing ri documentation for claide-1.0.2
Parsing documentation for colored2-3.1.2
Installing ri documentation for colored2-3.1.2
Parsing documentation for nanaimo-0.2.6
Installing ri documentation for nanaimo-0.2.6
Parsing documentation for xcodeproj-1.6.0
Installing ri documentation for xcodeproj-1.6.0
Parsing documentation for fir-cli-1.6.11
Installing ri documentation for fir-cli-1.6.11
Done installing documentation for thor, unf_ext, unf, domain_name, http-cookie, mime-types-data, mime-types, netrc, rest-client, rubyzip, ruby_android, chunky_png, rqrcode, CFPropertyList, oj, api_tools, atomos, claide, colored2, nanaimo, xcodeproj, fir-cli after 15 seconds
22 gems installed
➜  ~ fir help
Traceback (most recent call last):
	13: from /Users/lixinxing/.rvm/gems/ruby-2.5.1@global/bin/ruby_executable_hooks:24:in `<main>'
	12: from /Users/lixinxing/.rvm/gems/ruby-2.5.1@global/bin/ruby_executable_hooks:24:in `eval'
	11: from /usr/local/bin/fir:23:in `<main>'
	10: from /usr/local/bin/fir:23:in `load'
	 9: from /Users/lixinxing/.rvm/gems/ruby-2.5.1@global/gems/fir-cli-1.6.11/bin/fir:4:in `<top (required)>'
	 8: from /Users/lixinxing/.rvm/gems/ruby-2.5.1@global/gems/fir-cli-1.6.11/bin/fir:4:in `require_relative'
	 7: from /Users/lixinxing/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fir-cli-1.6.11/lib/fir.rb:23:in `<top (required)>'
	 6: from /Users/lixinxing/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /Users/lixinxing/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 4: from /Users/lixinxing/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fir-cli-1.6.11/lib/fir/util.rb:14:in `<top (required)>'
	 3: from /Users/lixinxing/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fir-cli-1.6.11/lib/fir/util.rb:14:in `require_relative'
	 2: from /Users/lixinxing/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fir-cli-1.6.11/lib/fir/util/publish.rb:3:in `<top (required)>'
	 1: from /Users/lixinxing/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/lixinxing/.rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- byebug (LoadError)
```

**Comment by z372183629** [comment]
更新到1.6.11后，我的也出现了类似的问题
```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- byebug (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.11/lib/fir/util/publish.rb:3:in `<top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.11/lib/fir/util.rb:14:in `require_relative'
	from /Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.11/lib/fir/util.rb:14:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.11/lib/fir.rb:23:in `<top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.11/bin/fir:4:in `require_relative'
	from /Library/Ruby/Gems/2.3.0/gems/fir-cli-1.6.11/bin/fir:4:in `<top (required)>'
	from /usr/local/bin/fir:22:in `load'
	from /usr/local/bin/fir:22:in `<main>'
```

**Comment by GuiLQing** [comment]
https://gems.ruby-china.org已经换成了https://gems.ruby-china.com了，是不是这里出了问题啊，现在Fir不能用

**Comment by jicheng1014** [comment]
实在抱歉  已经修复

**Comment by jicheng1014** [comment]
如有问题  还请联系微信  atpking
