### ISSUE TITLE
fir publish: Permission bits for '/Users/builder/.netrc' should be 0600, but are 644

### ISSUE THREAD

**Issue by jerryzhoujw** [FIRHQ/fir-cli#255]
Is this related to builder mac's file permission issue only ?
Is this any possible related to `fir-cli` ?
PS: is there any command line way to check if `fir-cli` is install fine.

shou

```log
+ fir publish a.ipa -s ss -c 'hiya' -T [token]
Permission bits for '/Users/builder/.netrc' should be 0600, but are 644
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/netrc-0.11.0/lib/netrc.rb:45:in `check_permissions'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/netrc-0.11.0/lib/netrc.rb:52:in `read'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:615:in `parse_url_with_auth!'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:83:in `initialize'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `new'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:66:in `block in basic_request'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:64:in `times'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:64:in `basic_request'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:10:in `block (2 levels) in <module:DefaultRestModule>'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fir-cli-2.0.0/lib/fir/util.rb:36:in `fetch_user_info'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fir-cli-2.0.0/lib/fir/util/publish.rb:192:in `initialize_publish_options'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fir-cli-2.0.0/lib/fir/util/publish.rb:11:in `publish'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fir-cli-2.0.0/lib/fir/cli.rb:126:in `publish'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fir-cli-2.0.0/lib/fir/cli.rb:173:in `invoke_command'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/Users/builder/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fir-cli-2.0.0/bin/fir:8:in `<top (required)>'
/Users/builder/.rbenv/versions/2.6.5/bin/fir:23:in `load'
/Users/builder/.rbenv/versions/2.6.5/bin/fir:23:in `<main>'
```

**Comment by jerryzhoujw** [comment]
it's fixed by `chmod 0600 /Users/builder/.netrc`, it not related to fir
