### ISSUE TITLE
undefined method `deep_symbolize_keys' for false:FalseClass

### ISSUE THREAD

**Issue by fishycx** [FIRHQ/fir-cli#263]
上传ipa 报错
```
undefined method `deep_symbolize_keys' for false:FalseClass
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.2/lib/fir/util/config.rb:21:in `config'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.2/lib/fir/util/login.rb:11:in `login'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.2/lib/fir/cli.rb:144:in `login'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.2/lib/fir/cli.rb:182:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.2/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:23:in `load'
/usr/local/bin/fir:23:in `<main>'
undefined method `deep_symbolize_keys' for false:FalseClass
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.2/lib/fir/util/config.rb:21:in `config'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.2/lib/fir/util/config.rb:38:in `current_token'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.2/lib/fir/util/publish.rb:208:in `initialize_publish_options'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.2/lib/fir/util/publish.rb:10:in `publish'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.2/lib/fir/cli.rb:135:in `publish'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.2/lib/fir/cli.rb:182:in `invoke_command'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/Library/Ruby/Gems/2.6.0/gems/fir-cli-2.0.2/bin/fir:8:in `<top (required)>'
/usr/local/bin/fir:23:in `load'
/usr/local/bin/fir:23:in `<main>'

```

**Comment by fishycx** [comment]
我同事的电脑也是这样，这两天突然出现的问题

**Comment by jicheng1014** [comment]
是不是您 ENV 的 HOME 出现了问题?    我们这个读取您Home 目录底下的 .fir-cli      如果您不确定  建议您先手动删除这个文件  之后用 fir-cli 再次登录下

**Comment by jicheng1014** [comment]
也可直用微信与我取得联系
