### ISSUE TITLE
admqr_knife  错误

### ISSUE THREAD

**Issue by sdaduanbilei** [FIRHQ/fir-cli#302]
```
[root@localhost ~]# fir help
/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:59:in `require': /usr/local/share/gems/gems/admqr_knife-0.1.5/lib/admqr_knife.rb:24: syntax error, unexpected ',' (SyntaxError)
    def visit(unique_code:, **options)
                           ^
/usr/local/share/gems/gems/admqr_knife-0.1.5/lib/admqr_knife.rb:53: syntax error, unexpected keyword_end, expecting end-of-input
	from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/share/gems/gems/fir-cli-2.0.10/lib/fir.rb:7:in `<top (required)>'
	from /usr/local/share/gems/gems/fir-cli-2.0.10/bin/fir:4:in `require_relative'
	from /usr/local/share/gems/gems/fir-cli-2.0.10/bin/fir:4:in `<top (required)>'
	from /usr/local/bin/fir:23:in `load'
	from /usr/local/bin/fir:23:in `<main>'
```

```
[root@localhost ~]# ruby -v
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
[root@localhost ~]#
```

在线等 大佬

**Comment by jicheng1014** [comment]
老哥   ruby 版本太老了  建议你使用rvm 升级下你的ruby 版本
