### ISSUE TITLE
undefined method `escape' for URI:Module

### ISSUE THREAD

**Issue by HectorHann** [FIRHQ/fir-cli#307]
Ruby Version = 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
Fir-cli  Version = fir-cli-2.0.10
Platform: CircleCI

运行命令：fir publish "$file" -T xxxxxxxx --oversea_turbo

错误提示：
```
undefined method `escape' for URI:Module
/usr/local/bundle/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:25:in `build_similar_get_request'
/usr/local/bundle/gems/api_tools-0.1.0/lib/api_tools/default_rest_module.rb:9:in `block (2 levels) in <module:DefaultRestModule>'
/usr/local/bundle/gems/fir-cli-2.0.10/lib/fir/util.rb:36:in `fetch_user_info'
/usr/local/bundle/gems/fir-cli-2.0.10/lib/fir/util/publish.rb:261:in `initialize_publish_options'
/usr/local/bundle/gems/fir-cli-2.0.10/lib/fir/util/publish.rb:11:in `publish'
/usr/local/bundle/gems/fir-cli-2.0.10/lib/fir/cli.rb:146:in `publish'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/bundle/gems/fir-cli-2.0.10/lib/fir/cli.rb:193:in `invoke_command'
/usr/local/bundle/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/usr/local/bundle/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/usr/local/bundle/gems/fir-cli-2.0.10/bin/fir:8:in `<top (required)>'
/usr/local/bundle/bin/fir:23:in `load'
/usr/local/bundle/bin/fir:23:in `<main>'

Exited with code exit status 1
```

**Comment by HectorHann** [comment]
大概三四天前，使用相同的配置，是可以成功的。

**Comment by foobra** [comment]
你 ruby 版本太新了, 需要降级, gem 还没更新

**Comment by jicheng1014** [comment]
哈哈  ruby 3.0 阿   这个得支持下
