### ISSUE TITLE
fir上传失败

### ISSUE THREAD

**Issue by rxwen** [FIRHQ/fir-cli#54]
应用环境：
mac osx 10.11.2
ruby 2.2.1p85
fir 1.4.5

用 fir publish /path/to/my/apk/file 命令上传，得到以下错误：
```

I, [2015-12-25T14:32:14.559737 #72279]  INFO -- : Publishing app via xxxxxx@gmail.com .......
I, [2015-12-25T14:32:14.560392 #72279]  INFO -- : ✈ -------------------------------------------- ✈
''
/Users/xxxxx/.rvm/gems/ruby-2.2.1/gems/ruby_android-0.7.7/lib/android/apk.rb:133:in `entry'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/gems/ruby_android-0.7.7/lib/android/apk.rb:115:in `file'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/gems/ruby_android-0.7.7/lib/android/apk.rb:165:in `icon'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/gems/fir-cli-1.4.5/lib/fir/util/parser/apk.rb:34:in `tmp_icons'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/gems/fir-cli-1.4.5/lib/fir/util/parser/apk.rb:16:in `full_info'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/gems/fir-cli-1.4.5/lib/fir/util/info.rb:35:in `apk_info'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/gems/fir-cli-1.4.5/lib/fir/util/publish.rb:12:in `publish'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/gems/fir-cli-1.4.5/lib/fir/cli.rb:104:in `publish'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/gems/fir-cli-1.4.5/lib/fir/cli.rb:169:in `invoke_command'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/gems/fir-cli-1.4.5/bin/fir:8:in `<top (required)>'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/bin/fir:23:in `load'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/bin/fir:23:in `<main>'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/xxxxx/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'

```
通过fir.im的网页上传没有问题。

**Comment by NaixSpirit** [comment]
报错的 log 不全吧? 把全部的 log 发到我邮件里吧, hxy@fir.im

**Comment by rxwen** [comment]
只有这些了。这是完整的log。

**Comment by rxwen** [comment]
尝试加了 -V 参数，也是这些。

**Comment by rxwen** [comment]
看log似乎跟apk的icon有关，工具对apk的内容有要求吗？

**Comment by NaixSpirit** [comment]
估计是没有发现 apk 包里面的 icon, 所以报错了
可以先用 `fir i  /path/to/my/apk/file` 看看

**Comment by rxwen** [comment]
```
I, [2015-12-25T15:05:07.577724 #74788]  INFO -- : Analyzing apk file......
I, [2015-12-25T15:05:07.577823 #74788]  INFO -- : ✈ -------------------------------------------- ✈
I, [2015-12-25T15:05:09.867902 #74788]  INFO -- : type: android
I, [2015-12-25T15:05:09.867960 #74788]  INFO -- : identifier: com.hello.ui
I, [2015-12-25T15:05:09.867989 #74788]  INFO -- : name: test
I, [2015-12-25T15:05:09.868006 #74788]  INFO -- : build: 1
I, [2015-12-25T15:05:09.868022 #74788]  INFO -- : version: 1.0.0
I, [2015-12-25T15:05:09.868037 #74788]  INFO -- :
```

**Comment by rxwen** [comment]
-i 检查没有提示什么错误

**Comment by NaixSpirit** [comment]
抱歉应该是 `fir i /path/to/my/apk/file -a`

**Comment by rxwen** [comment]
跟之前相同的错误。那是我的apk不符合要求咯？
我没有指定icon，是默认的

**Comment by NaixSpirit** [comment]
把这个 app 在网页上的短链接发我看看

**Comment by rxwen** [comment]
http://fir.im/v62w

**Comment by rxwen** [comment]
我指定了application的icon之后，就可以了。虽然可以解决问题，不过我以为这个要求不一定是必须的。

**Comment by NaixSpirit** [comment]
是的, 我得改改解析 apk 使用的包

**Comment by NaixSpirit** [comment]
[fixd](https://github.com/FIRHQ/fir-cli/issues/77)

**Comment by wangxl056** [comment]
> 我指定了application的icon之后，就可以了。虽然可以解决问题，不过我以为这个要求不一定是必须的。

怎么指定application的icon?
